

    create table automobile (
        id bigint generated by default as identity,
        version bigint not null,
        date_created timestamp not null,
        last_updated timestamp not null,
        make varchar(255) not null,
        model varchar(255) not null,
        owner_id bigint not null,
        vin bigint not null,
        year integer not null,
        primary key (id)
    );

    create table listing (
        id bigint generated by default as identity,
        version bigint not null,
        automobile_id bigint not null,
        buyer_id bigint,
        date_created timestamp not null,
        is_active boolean not null,
        last_updated timestamp not null,
        price decimal(19,2) not null,
        seller_id bigint not null,
        primary key (id)
    );

    create table role (
        id bigint generated by default as identity,
        version bigint not null,
        authority varchar(255) not null,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity,
        version bigint not null,
        account_expired boolean not null,
        account_locked boolean not null,
        age integer not null,
        bio varchar(255),
        email varchar(255),
        enabled boolean not null,
        first_name varchar(255),
        last_name varchar(255),
        "password" varchar(255) not null,
        password_expired boolean not null,
        username varchar(255) not null,
        primary key (id)
    );

    create table user_role (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    alter table automobile 
        add constraint UK_9ds6fw9jcxa2d86pc6qfsldab  unique (vin);

    alter table listing 
        add constraint UK_blqc2qnsv34vdij2wdcja6hp1  unique (automobile_id);

    alter table role 
        add constraint UK_irsamgnera6angm0prq1kemt2  unique (authority);

    alter table user 
        add constraint UK_sb8bbouer5wak8vyiiy4pf2bx  unique (username);

    alter table automobile 
        add constraint FK_yaixhdofc2ahbvo87f4kxnfd 
        foreign key (owner_id) 
        references user;

    alter table listing 
        add constraint FK_blqc2qnsv34vdij2wdcja6hp1 
        foreign key (automobile_id) 
        references automobile;

    alter table listing 
        add constraint FK_mr2wlvmjao25kosdrj07sx6x5 
        foreign key (buyer_id) 
        references user;

    alter table listing 
        add constraint FK_3fd1l12tydngsg3jk09360exu 
        foreign key (seller_id) 
        references user;

    alter table user_role 
        add constraint FK_it77eq964jhfqtu54081ebtio 
        foreign key (role_id) 
        references role;

    alter table user_role 
        add constraint FK_apcc8lxk2xnug8377fatvbn04 
        foreign key (user_id) 
        references user;
